export const generalConstant = {
    SOMETING_WENT_WRONG: 'Something went wrong, please try again later.',
    TYPE_NOT_FOUND: 'Type not found',
    CATEGORY_NOT_FOUND: 'Category not found',
    USER_NOT_FOUND: 'User not found',
    PRODUCT_NOT_FOUND: 'Product not found',
    CURRICULUM_NOT_FOUND: 'Curriculum not found',
    ORDER_NOT_FOUND: 'Order not found',
    MIDTRANS_ERROR: 'Midtrans payment gateway error',
    BALANCE_NOT_ENOUGH: 'Balance is not enough',
    WITHDRAW_MESSAGE: 'Withdrawal request received, please wait for admin approval',
    PRODUCT_ALREADY_EXISTS: 'Product already exists',
    WITHDRAW_SATUS_INVALID: 'Withdraw status is invalid',
    VOUCHER_NOT_FOUND: 'Voucher not found',
    VOUCHER_EXPİRED: 'Voucher has expired',
    VOUCHER_CODE_ALREADY_EXISTS: 'Voucher code already exists',
    ECOURSE_SUB_MATERIAL_NOT_FOUND: 'E-course sub material not found',
    RATING_ALREADY_EXISTS: 'You have already rated this product',
}